id: 6120aaf163c24a589fb9ebbd4e1090ee
initial_creation_type: ebook
created_at: 8/04/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmp7vnvihqd.jpg
  credit: tmp2vgp6t2h.jpg
